import type { TablerIconComponent } from "vue-tabler-icons";
type Attendance = {
    avatar: string;
    name:string;
    class: string;
    day1:TablerIconComponent;
    day2:TablerIconComponent;
    day3:TablerIconComponent;
    day4:TablerIconComponent;
    day5:TablerIconComponent;
    day6:TablerIconComponent;
    day7:TablerIconComponent;
    day8:TablerIconComponent;
    day9:TablerIconComponent;
    day10:TablerIconComponent;
    day11:TablerIconComponent;
    day12:TablerIconComponent;
    day13:TablerIconComponent;
    day14:TablerIconComponent;
    day15:TablerIconComponent;
    day16:TablerIconComponent;
    day17:TablerIconComponent;
    day18:TablerIconComponent;
    day19:TablerIconComponent;
    day20:TablerIconComponent;
    day21:TablerIconComponent;
    day22:TablerIconComponent;
    day23:TablerIconComponent;
    day24:TablerIconComponent;
    day25:TablerIconComponent;
    day26:TablerIconComponent;
    day27:TablerIconComponent;
    day28:TablerIconComponent;
    day29:TablerIconComponent;
    day30:TablerIconComponent;
};

export type { Attendance };